description: hg38 snakemake configuration file
assembly: hg38

samples: &samples
       - C3647 
       - C3649
       - C3651
       - C4955
       - C8861
       - C40280
       - H19101
       - H20961
       - H28834
       - HUtt45
       - H19114
       - HUtt60

merged_sample: &merged_sample 'merged_sample' ## this will combine all the 12 samples into a 13th file
augmented_samples: 
       - [*merged_sample]
       - *samples
CLUSTER: 'env/cluster.yaml'
index_genome_dir: "data/Index_genome/hg38"
genome_size: 2913022398
chrom_sizes: 'data/Index_genome/hg38.chrom.sizes'
genome2bit_index: "data/Index_genome/hg38.2bit" 
blacklist: "../data/ENCODE_blacklisted/hg38_blacklist_v2.bed"

## tmp dir for Deeptools
tmp_dir: /data/scratch/projects/punim0586/dvespasiani
