##==========================##
## cluster config arguments ##
##==========================##
snakefile: snakefile.smk
cluster:
  sbatch
    --cpus-per-task={resources.threads}
    --partition={resources.partition}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name={rule}
    --output=slurm-report/{rule}_{jobid}.out
    --error=slurm-report/{rule}_{jobid}.err
    --parsable
default-resources:
  - mem_mb=20000
  - time=500
  - partition=regular
  - threads=1
jobs: 5
latency-wait: 60
cores: 5
restart-times: 1
max-jobs-per-second: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True
show-failed-logs: True
reason: True
cluster-status: slurm-status.py
max-status-checks-per-second: 10
# localrules: all
