description: Configuration file for preprocessing bulk ATAC-seq datasets
author: Davide Vespasiani
project: atac-pipeline 

##==========================##
##     Project I/O dirs     ##
##==========================##
## list here all project main input/output directories
project_config: {
    baseDir:  /stornext/General/data/user_managed/grpu_jchoi_0/projects/davide,
    project: atac-pipeline, ## change this
    datadir: data/subsampled-files/, ## change this to whichever is your input dir containing fastq files
    outdir: out/,
    qcdir: out/qc/,
    logs: logs/,
    plots: out/plots/,
    tables: out/tables/,
    tmp_dir:  /vast/scratch/users/vespasiani.d/
}

##=============================##
## Parameters interactive sess ##  
##=============================##
## list here all the config parameters to run an interactive session on SLURM
interactive_sess: {
    ntasks: 1,
    threads: 1,
    cpus_per_task: 1,
    mem: 280G,
    time: 480,
    partition: regular,
    modules: config/modules.txt
}

##==================##
##  ATAC specifics  ##
##==================##
## list here all specifics of atac experiment
atac_specifics: {
    read_length: 65,
    adapters: data/adapters/NexteraPE-PE.fa
}

##==================##
##  Species info    ##
##==================##
## list here all the specifics for your species
species_info: {
    species: musmusculus,
    assembly: mm10,
    genome_size: 2652783500,
    chrom_sizes: '/wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10/mm10.chrom.sizes.txt',
    standard_chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,'X','Y'],
    genome2bit_index: /wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10_bowtie_index/mm10.2bit,
    genome_index: /wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10_bowtie_index/mm10,
    blacklist: /wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10/mm10.blacklist.new.bed
}

##==================##
##     Samples      ##
##==================##
## list here all the sample basenames without the read extension 
samples: &samples
       - Ad2_1_S1_L001
       - Ad2_3_S2_L001
       - Ad2_4_S3_L001
       - Ad2_6_S4_L001
       - Ad2_7_S5_L001
       - Ad2_9_S6_L001
       - Ad2_10_S7_L001
       - Ad2_11_S8_L001

## these lines below will combine all the samples into a single big sample file
## to make snakemake combining all the aligned and filtered reads into a one big file and call accessible chromatin peaks also on this one
all_samples: &all_samples 'all_samples'
combined_sample: 
       - [*all_samples]
       - *samples

##===================##
## ENCODE parameters ##
##===================##
## list here all parameters for data quality control 

## read quality
read_minQ: 30

## MACS2 peak caller
npeaks: 300000
fragment_size: 150
shift: -75
pval_thresh: 0.01

##===================##
##  Snakemake Rules  ##
##===================##
## list here all names of snakemake rules 
fastqc: fastqc
trim-adapter: trim-adapter
align: alignment
deeptools: deeptools
peak-calling: peak-calling
consensus-peak: consensus-peak
atac-qc: atac-qc 
