description: Snakemake configuration file for ATAC-seq preprocessing

species: mus musculus
assembly: mm10

basedir: /wehisan/general/user_managed/grpu_jchoi_0/

fastqdir: /wehisan/general/user_managed/grpu_jchoi_0/projects/davide/atac-pipeline/data/subsampled-files/
genome_index: /wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10_bowtie_index/mm10

blacklist: /wehisan/general/user_managed/grpu_jchoi_0/genomes/Mouse/mm10/mm10.blacklist.new.bed

genome_size: 2652783500
read_length: 65

adapters: /wehisan/general/user_managed/grpu_jchoi_0/projects/davide/atac-pipeline/data/adapters/NexteraPE-PE.fa

samples: 
       - Ad2_10_S7_L001
       - Ad2_11_S8_L001
       - Ad2_1_S1_L001



